theme: "Chirpy"
name: "BlogFeather"
discription: "Share live stories."
footer-links: 
    zhihu: BCfeather
    email: baocz2008@outlook.com
    twitter: CaozheB72170
gitalk:
    clientID: Iv1.2886b3c78d59f28f
    clientSecret: a5af94f0e0aabf878256ce37395d8071bfb78859
    repo: BCFeather.github.io
    owner: BCFeather    
